// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ramicmfsdywohgftyzxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhbWljbWZzZHl3b2hnZnR5enhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMzY0MjUsImV4cCI6MjA3MDYxMjQyNX0.0TQJKEZQNk4Btvkv0TI3tTV3jo4jILfZEHeWvs-fA7M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});